### ISSUE TITLE
Remove and add film

### ISSUE THREAD

**Issue by zarevskaya** [zoriya/Kyoo#308]
### Kyoo's version

The last

### What happened?

Hello, when you remove a film and add it later, Kyoo no longer offers it for playback.

**Comment by zoriya** [comment]
Kyoo tracks file systems events, if you create a movie and then delete the old version it won't show for now. It you restart the scanner (run `docker compose restart scanner`), it will scan again and show it. I plan on writting an admin dashboard soon to make this kind of issues easier to deal with.

**Comment by zarevskaya** [comment]
Merci! Je fais un article sur ton application donc j'essaye vraiment de bien tout comprendre afin de restituer sa valeur au maximum.

**Comment by zoriya** [comment]
J'ai compris pourquoi un film retire ne peut pas être ajouté, je vais fix ça dans la soirée.

Je n'arrive pas à reproduire l'erreur que tu as eu au-dessus, par contre, tu peux me donner plus de logs ?

**Comment by zarevskaya** [comment]
Ah, super :) 
Oui bien entendu:

` File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host back:5000 ssl:default [Connect call failed ('192.168.16.6', 5000)]
INFO:root:Starting the scan. It can take some times...
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1119, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1101, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1004, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 647, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 687, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.16.6', 5000)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/scanner/__main__.py", line 6, in <module>
    asyncio.run(scanner.main())
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/scanner/__init__.py", line 44, in main
    await scanner.scan(path)
  File "/app/scanner/scanner.py", line 43, in scan
    self.registered = await self.get_registered_paths()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/scanner/scanner.py", line 59, in get_registered_paths
    async with self._client.get(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host back:5000 ssl:default [Connect call failed ('192.168.16.6', 5000)]
INFO:root:Starting the scan. It can take some times...
INFO:root:Identied /video/Sammy 2 (2012).mkv: MatchesDict({'title': 'Sammy 2', 'year': 2012, 'container': 'mkv', 'mimetype': 'video/x-matroska', 'type': 'movie'})
INFO:root:Identied /video/Penguins of Madagascar (2014) [1080p] MULTi BluRay x264-PopHD.mkv: MatchesDict({'title': 'Penguins of Madagascar', 'year': 2014, 'screen_size': '1080p', 'source': 'Blu-ray', 'video_codec': 'H.264', 'release_group': 'PopHD', 'container': 'mkv', 'mimetype': 'video/x-matroska', 'type': 'movie'})
ERROR:root:Unhandled error
Traceback (most recent call last):
  File "/app/scanner/utils.py", line 26, in internal
    await f(*args, **kwargs)
  File "/app/scanner/scanner.py", line 97, in identify
    movie_id = await self.post("movies", data=movie.to_kyoo())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/scanner/scanner.py", line 231, in post
    and ret["airDate"][:4] != str(data["air_date"].year)
        ~~~^^^^^^^^^^^
KeyError: 'airDate'
ERROR:root:Unhandled error
Traceback (most recent call last):
  File "/app/scanner/utils.py", line 26, in internal
    await f(*args, **kwargs)
  File "/app/scanner/scanner.py", line 97, in identify
    movie_id = await self.post("movies", data=movie.to_kyoo())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/scanner/scanner.py", line 231, in post
    and ret["airDate"][:4] != str(data["air_date"].year)
        ~~~^^^^^^^^^^^
KeyError: 'airDate'
INFO:root:Scan finished. Starting to monitor..`

**Comment by zoriya** [comment]
Merci du report, tu peux update kyoo et le bug devrait etre regle.
